services:
  app:
    build: .
    container_name: nasa_app
    env_file:
      - .env    # DATABASE_URL comes from here
    ports:
      - "5000:5000"

  grafana:
    image: grafana/grafana:latest
    container_name: nasa_grafana
    ports:
      - "4000:3000"
